Java sample program
WPIRoboticsProjects/GRIP-code-generation pull request #7
Opened 2017-01-19 03:29 UTC by KeithRieck

I've added a sample application for running GRIP pipelines in Java.  I have tested this on Windows, Mac, Ubuntu, and Raspbian.

2017-01-19 04:26 UTC, SamCarlberg requested changes
Thanks for doing this! There's a few small things I'd like addressed, but on the whole this is very good

2017-01-19 04:26 UTC, SamCarlberg commented on java/src/main/java/edu/wpi/first/wpilibj/vision/VideoViewer.java
> +		} catch (ClassNotFoundException e) {
Use a multicatch

2017-01-19 04:26 UTC, SamCarlberg commented on java/README.md
> +## Installing OpenCV on Windows
Could mention the opencv-installer program we've written that downloads and installs WPI's prebuilt bindings. No need to compile OpenCV yourself (for the most part -- it only does x86_64 windows, linux, and OS X, with support for generic linux armhf and rasbian coming soon)

2017-01-19 04:26 UTC, SamCarlberg commented on java/src/main/java/grip/sample1/FindRedAreasApp.java
> +	final Listener<? super FindRedAreas> listener;
This should just be

```java
final Listener<FindRedAreas> listener;
```

2017-01-19 04:26 UTC, SamCarlberg commented on java/src/main/java/grip/sample1/FindRedAreasApp.java
> +		this.gripRunner = new GripRunner<FindRedAreas>(
`<FindRedAreas>` is redundant, just use the diamond operator `<>`

2017-01-19 16:16 UTC, JLLeitschuh commented on java/src/main/java/edu/wpi/first/wpilibj/vision/GripRunner.java
> +		while (true) {
This should check if the thread's interrupted flag has been set.
```
while(!Thread.currentThread().isInterrupted())`
```

2017-01-19 16:18 UTC, JLLeitschuh commented
This overall looks really good. Thank you for your contribution.
If you could clean up the things that I and @SamCarlberg have requested that would be awesome!

2017-01-20 03:18 UTC, KeithRieck commented
OK, I've pushed fixes.

2017-01-20 03:22 UTC, KeithRieck commented
OK, I think I've got everything fixed.
I'm not sure if I need to resubmit the pull request though. ---- Keith Rieck rieck_55113@yahoo.com

      From: Jonathan Leitschuh <notifications@github.com>
 To: WPIRoboticsProjects/GRIP-code-generation <GRIP-code-generation@noreply.github.com> 
Cc: Keith Rieck <rieck_55113@yahoo.com>; Author <author@noreply.github.com>
 Sent: Thursday, January 19, 2017 10:18 AM
 Subject: Re: [WPIRoboticsProjects/GRIP-code-generation] Java sample program (#7)
   
This overall looks really good. Thank you for your contribution.
If you could clean up the things that I and @SamCarlberg have requested that would be awesome!—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2017-01-20 03:46 UTC, SamCarlberg approved these changes

2017-01-20 03:46 UTC, merged